[project]
name = "thsensor"
version = "2026.3.1"
description = "Simple smart sensor based on Raspberry Pi Pico 2 W written in MicroPython."
readme = "readme.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mpremote>=1.27.0",
    "mpy-cross>=1.27.0.post2",
    "pytest>=9.0.2",
    "pytest-mock>=3.15.1",
]
